Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,6 +45,8 @@ jobs:
           name: "Get JWT Token and Store"
           command: |
             echo "Fetching JWT token..."
+            export REGISTER_PAYLOAD='{ "username": "testuser", "accountNumber": "123456", "password": "password", "role": "customer" }'
+            curl -s -X POST http://localhost:3001/users/register -H "Content-Type: application/json" -H "X-CSRF-Token: $CSRF_TOKEN" -d "$REGISTER_PAYLOAD"
             export LOGIN_PAYLOAD='{ "username": "testuser", "accountNumber": "123456", "password": "password" }'
             export JWT_TOKEN=$(curl -s -X POST http://localhost:3001/users/login -H "Content-Type: application/json" -H "X-CSRF-Token: $CSRF_TOKEN" -d "$LOGIN_PAYLOAD" | jq -r '.token')
             if [ -z "$JWT_TOKEN" ] || [ "$JWT_TOKEN" == "null" ];then
@@ -60,6 +62,8 @@ jobs:
             curl --fail http://localhost:3001/users/login || (echo "Login endpoint failed!" && exit 1)
             curl --fail -H "Authorization: Bearer $JWT_TOKEN" http://localhost:3001/payments || (echo "Payments endpoint failed!" && exit 1)
             curl --fail -H "Authorization: Bearer $JWT_TOKEN" http://localhost:3001/employee/payments || (echo "Employee payments endpoint failed!" && exit 1)
+            curl --fail -H "Authorization: Bearer $JWT_TOKEN" -X PATCH http://localhost:3001/employee/payments/1/verify || (echo "Verify payment endpoint failed!" && exit 1)
+            curl --fail -H "Authorization: Bearer $JWT_TOKEN" -X POST http://localhost:3001/employee/payments/submit-swift || (echo "Submit payments to SWIFT endpoint failed!" && exit 1)
             echo "Backend tests completed successfully."
 
   # Job for frontend testing and setup
